vim.keymap.set("n", "<leader>cp", function()
	local directory_path = vim.fn.expand("%:p:h")
	vim.fn.setreg("+", '"' .. directory_path .. '"')
	vim.notify("'" .. directory_path .. "'\ncopied to clipboard", vim.log.levels.INFO)
end, { noremap = true, silent = true, desc = "[C]opy [P]ath to current file directory" })

vim.keymap.set("n", "<leader>cP", function()
	local current_file_path = vim.fn.expand("%:p")
	vim.fn.setreg("+", '"' .. current_file_path .. '"')
	vim.notify("'" .. current_file_path .. "'\ncopied to clipboard", vim.log.levels.INFO)
end, { noremap = true, silent = true, desc = "[C]opy [P]ath to current file" })
